export interface Product {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  ingredients: string;
  delivery: string;
  howToUse: string;
  imageUrl: string;
  productLink: string;
  category: string;
}

export const products: Product[] = [
  {
    id: 'product-1',
    title: 'TensioLift Lifting Serum',
    subtitle: 'Anti-aging lifting effect serum',
    description: 'CLINICALLY PROVEN EFFICACY: -40% WRINKLES FROM DAY 28*. 100% natural alternative to injections and invasive techniques, this clean and vegan serum targets expression lines and wrinkles through action on neuroreceptors. The TensioLift serum contains Argireline® at 10% concentration. This ultra-technical peptide was specifically designed to inhibit nerve signal transmission to muscles. The goal? Relax muscles and limit their contractions to smooth expression lines and wrinkles. Combined with Matrixyl® and vegetable collagen, two actives that stimulate collagen production, the formula instantly replumps skin, smooths wrinkles and prevents their appearance. To amplify the effects, our facialists developed an exclusive self-massage protocol. Result: existing wrinkles and fine lines are smoothed, skin is firmed, muscles contract less so wrinkles appear more slowly and are less deep.',
    ingredients: 'Aqua (Water), Pentylene glycol, Propanediol, Decylcocoate, Lauroyl lysine, C14-22 alcohols, Parfum (Fragrance), Sodium benzoate, Maltodextrin, Lepidium meyenii root extract, C12-20 alkyl glucoside, Xanthan gum, Hydrolyzed vegetable protein, Citric acid, Gellan gum, Leuconostoc/radish root ferment filtrate, Glycine soja (Soybean) oil, Acetyl hexapeptide-8, Caprylyl glycol, Tocopherol, N-prolyl palmitoyl tripeptide-56',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Scan the QR code on the product packaging or access the self-massage protocol sent by email. Apply 3 to 4 drops on the face and décolleté morning and/or evening and massage until fully absorbed. Choose the zone(s) to target and create your own self-massage routine. Repeat this self-massage routine every day to maximize anti-aging effects.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/SerumTensioLiftPackshotavecombrecopie.png',
    productLink: 'https://seasonly.fr/collections/shop/products/serum-tensiolift-copy',
    category: 'Serums',
  },
  {
    id: 'product-2',
    title: 'TensioLift Oil',
    subtitle: 'Anti-aging lifting effect oil',
    description: 'CLINICALLY PROVEN EFFICACY: -18% WRINKLES FROM DAY 28*. 100% natural alternative to injections, this clean and vegan formula enriched with Spilanthes was developed to act on 8 signs of skin aging. TensioLift Oil combines patented Lift Oléo-Actif technology with an exclusive self-massage protocol. It smooths wrinkles and fine lines, firms skin, redefines facial contours and restores radiance. Result: visibly younger and firmer skin from 28 days of use.',
    ingredients: 'Caprylic/capric triglyceride, Simmondsia chinensis (Jojoba) seed oil, Prunus amygdalus dulcis (Sweet almond) oil, Tocopherol, Helianthus annuus (Sunflower) seed oil, Spilanthes acmella flower/leaf/stem extract, Parfum (Fragrance), Limonene, Linalool',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Scan the QR code on the packaging or access the self-massage protocol sent by email. Apply 3 to 4 drops on face and neck morning and/or evening. Massage following the exclusive self-massage protocol to amplify results.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/HuileTensioLiftPackshot30mlLiftOleoactifavecombre.png',
    productLink: 'https://seasonly.fr/collections/shop/products/huile-tensiolift',
    category: 'Oils',
  },
  {
    id: 'product-3',
    title: 'TensioLift Day Cream',
    subtitle: 'Anti-aging lifting and anti-spot day cream',
    description: 'New. TensioLift Day Cream is an anti-aging cream enriched with Argireline® and anti-spot actives. It acts on wrinkles, firms skin and evens complexion by visibly reducing pigmentation spots. Its melting texture suits all skin types. Clinically proven effective from 28 days.',
    ingredients: 'Aqua (Water), Glycerin, Caprylic/capric triglyceride, Cetearyl alcohol, Niacinamide, Cetearyl glucoside, Butyrospermum parkii (Shea) butter, Pentylene glycol, Acetyl hexapeptide-8, Sodium hyaluronate, Tocopherol, Parfum (Fragrance), Xanthan gum, Citric acid, Sodium benzoate',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply in the morning on clean, dry skin. Massage gently until fully absorbed. Can be used alone or under makeup.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/Creme_TensioLift_Packshot.png',
    productLink: 'https://seasonly.fr/collections/shop/products/creme-de-jour-tensiolift',
    category: 'Creams',
  },
  {
    id: 'product-4',
    title: 'Night Oil',
    subtitle: 'Repairing face oil',
    description: 'Best Seller. Seasonly Night Oil is a repairing face oil that nourishes, regenerates and repairs skin during sleep. Its 100% natural formula enriched with vegetable retinol (bakuchiol) and rose hip oil acts on wrinkles, dull complexion and loss of firmness. Available in 15ml and 30ml. Result: in the morning, skin is nourished, replumped and radiant.',
    ingredients: 'Rosa canina fruit oil, Argania spinosa kernel oil, Squalane, Helichrysum italicum flower extract, Bakuchiol, Tocopherol, Parfum (Fragrance), Limonene, Linalool, Geraniol, Citronellol',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply 3 to 5 drops on clean face and neck in the evening. Massage until fully absorbed. For enhanced effects, combine with a gua sha or massage roller.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/HuiledeNuit30ml.png',
    productLink: 'https://seasonly.fr/collections/shop/products/huile-de-nuit',
    category: 'Oils',
  },
  {
    id: 'product-5',
    title: 'Quartz Gua Sha',
    subtitle: 'Firming massage accessory',
    description: 'The Seasonly Quartz Gua Sha is a facial massage tool crafted from authentic rose quartz. Used with Night Oil or any skincare oil, it drains toxins, depuffs the face, firms facial contours and reduces swelling. Ideal for an effective anti-aging gua sha ritual.',
    ingredients: 'N/A - Accessoire en quartz rose naturel',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil on the face. Use the gua sha by gently gliding it over the skin, following lymphatic drainage directions. Perform slow, firm movements from bottom to top and inside to outside. Use a minimum 2 to 3 times a week.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/GuaShaQuartz_54893903-1d23-4489-b18f-48eb1dc611e5.png',
    productLink: 'https://seasonly.fr/collections/shop/products/quartz-gua-sha',
    category: 'Accessories',
  },
  {
    id: 'product-6',
    title: 'Cleansing Oil',
    subtitle: 'Facial cleansing oil',
    description: 'Seasonly Cleansing Oil is a gentle cleansing oil that effectively removes makeup, impurities and excess sebum while respecting the skin\'s hydrolipidic film. Its 100% natural formula enriched with sunflower and jojoba oil leaves skin clean, soft and comfortable. Suitable for all skin types, including sensitive skin.',
    ingredients: 'Helianthus annuus (Sunflower) seed oil, Simmondsia chinensis (Jojoba) seed oil, Prunus amygdalus dulcis (Sweet almond) oil, Tocopherol, Parfum (Fragrance)',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply the cleansing oil on dry skin. Massage gently to dissolve makeup and impurities. Rinse with warm water or remove with a damp cotton pad. Can be used alone or as the first step of a double cleanse.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/HuileDemaquillante.png',
    productLink: 'https://seasonly.fr/collections/shop/products/huile-demaquillante',
    category: 'Oils',
  },
  {
    id: 'product-7',
    title: 'Facial Cleansing Gel',
    subtitle: 'Soothing facial cleansing gel',
    description: 'Seasonly Facial Cleansing Gel is a gentle gel-texture cleanser that deeply cleanses while respecting the skin barrier. Enriched with aloe vera and soothing actives, it removes impurities, excess sebum and pollution traces without drying skin out. Suitable for all skin types.',
    ingredients: 'Aqua (Water), Aloe barbadensis leaf juice, Glycerin, Cocamidopropyl betaine, Sodium lauroyl methyl isethionate, Parfum (Fragrance), Panthenol, Allantoin, Sodium benzoate, Citric acid',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply cleansing gel on damp face. Massage gently in circular movements. Rinse thoroughly with warm water. Use morning and/or evening.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/GeleeNettoyante_8af51eba-a28f-4f93-ab17-f03279905fe7.png',
    productLink: 'https://seasonly.fr/collections/shop/products/gelee-nettoyante-visage',
    category: 'Cleansers',
  },
  {
    id: 'product-8',
    title: 'De-Puffing Eye Serum',
    subtitle: 'Anti-dark circle eye contour serum',
    description: 'Best Seller. Seasonly De-Puffing Eye Serum is an eye contour serum formulated to reduce dark circles, depuff bags and smooth fine lines. Its formula enriched with caffeine, peptides and hyaluronic acid works visibly from the first uses. The eye area looks more rested, luminous and youthful.',
    ingredients: 'Aqua (Water), Glycerin, Niacinamide, Caffeine, Sodium hyaluronate, Panthenol, Acetyl tetrapeptide-5, Tocopherol, Allantoin, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a small amount of serum around the eye area morning and evening. Pat gently with fingertips until fully absorbed. Avoid direct contact with eyes.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/SerumRegard.png',
    productLink: 'https://seasonly.fr/collections/shop/products/serum-regard',
    category: 'Serums',
  },
  {
    id: 'product-9',
    title: 'Blemish Serum',
    subtitle: 'Anti-blemish face serum',
    description: 'Best Seller. Seasonly Blemish Serum is a face serum formulated to reduce blemishes, tighten pores and regulate sebum production. Enriched with niacinamide, salicylic acid and purifying actives, it targets pimples, blackheads and excess shine. Available in 15ml and 30ml. Suitable for oily to combination skin.',
    ingredients: 'Aqua (Water), Niacinamide, Glycerin, Zinc gluconate, Salicylic acid, Panthenol, Centella asiatica extract, Sodium hyaluronate, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply blemish serum on clean face, morning and/or evening. Target areas (blemishes, enlarged pores). Allow to absorb before applying your moisturizer.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/SerumImperfections_ad9598d4-2ce9-425c-90ae-57631aa2e19a.png',
    productLink: 'https://seasonly.fr/collections/shop/products/serum-imperfections',
    category: 'Serums',
  },
  {
    id: 'product-10',
    title: 'New Skin Mask',
    subtitle: 'Gentle fruit enzyme exfoliating mask',
    description: 'Seasonly New Skin Mask is a gentle exfoliating mask enriched with fruit enzymes (papaya, pineapple) that gently removes dead skin cells without aggression. It instantly reveals smoother, more luminous and more even skin. Its formula nourishes and hydrates at the same time as it exfoliates, for a new skin result visible from the first use.',
    ingredients: 'Aqua (Water), Kaolin, Glycerin, Carica papaya (Papaya) fruit extract, Ananas sativus (Pineapple) fruit extract, Saccharomyces ferment, Cetearyl alcohol, Butyrospermum parkii (Shea) butter, Sodium benzoate, Citric acid, Parfum (Fragrance)',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a thick layer on clean, dry face, avoiding the eye area. Leave on for 10 to 15 minutes. Rinse thoroughly with warm water. Use 1 to 2 times a week.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/MasquePeauNeuve_7700ce20-fec0-4adf-b8e5-a4bd6f6b7b34.png',
    productLink: 'https://seasonly.fr/collections/shop/products/masque-peau-neuve',
    category: 'Masks',
  },
  {
    id: 'product-11',
    title: 'Fluid Cream',
    subtitle: 'For normal to combination skin',
    description: 'Seasonly Fluid Cream is a lightweight moisturizer formulated for normal to combination skin. Its fluid, non-greasy texture hydrates without weighing down, mattifies oily zones while nourishing dry areas. Enriched with hyaluronic acid and niacinamide, it smooths skin texture and evens complexion.',
    ingredients: 'Aqua (Water), Glycerin, Cyclopentasiloxane, Niacinamide, Dimethicone, Cetearyl alcohol, Sodium hyaluronate, Tocopherol, Parfum (Fragrance), Carbomer, Sodium hydroxide, Phenoxyethanol',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply fluid cream morning and/or evening on clean face. Massage gently until fully absorbed. Suitable as a base under makeup.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/CremeFluide_2b6b0599-8d20-4ba9-8d95-2887e188d154.png',
    productLink: 'https://seasonly.fr/collections/shop/products/la-creme-fluide',
    category: 'Creams',
  },
  {
    id: 'product-12',
    title: 'Tan Boost Oil',
    subtitle: 'Healthy glow oil',
    description: 'New. Seasonly Tan Boost Oil is a healthy glow oil that instantly gives a natural sun-kissed effect. Its formula enriched with natural self-tanning actives and precious oils nourishes skin while giving it a golden radiance. Ideal for sunless days or to maintain a tan.',
    ingredients: 'Caprylic/capric triglyceride, Simmondsia chinensis (Jojoba) seed oil, Helianthus annuus (Sunflower) seed oil, Dihydroxyacetone, Tocopherol, Parfum (Fragrance), Beta-carotene',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops on face and/or body by massaging until absorbed. Can be mixed with your regular cream for a subtle healthy glow effect. Avoid the eye contour.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/Sanstitre-1_1.png',
    productLink: 'https://seasonly.fr/collections/shop/products/huile-tan-boost',
    category: 'Oils',
  },
  {
    id: 'product-13',
    title: 'Anti-Aging Eye Cream',
    subtitle: 'Hydrating anti-wrinkle cream',
    description: 'Seasonly Anti-Aging Eye Cream is a hydrating and anti-aging eye cream targeting fine lines, dark circles and puffiness. Its formula enriched with peptides, vegetable retinol and hyaluronic acid replumps skin, reduces signs of fatigue and prevents premature aging around the eyes.',
    ingredients: 'Aqua (Water), Glycerin, Caprylic/capric triglyceride, Cetearyl alcohol, Sodium hyaluronate, Caffeine, Bakuchiol, Acetyl tetrapeptide-5, Tocopherol, Allantoin, Carbomer, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a pea-sized amount around the eyes morning and evening. Gently tap with ring finger until fully absorbed. Avoid direct contact with eyes.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/CremeYeuxAnti-Age.png',
    productLink: 'https://seasonly.fr/collections/shop/products/creme-yeux-anti-age',
    category: 'Creams',
  },
  {
    id: 'product-14',
    title: 'Anti-Thirst Serum',
    subtitle: 'Hydrating face serum',
    description: 'Out of Stock. Seasonly Anti-Thirst Serum is an intensive hydrating serum formulated for dehydrated skin. Enriched with multi-molecular hyaluronic acid and hydrating actives, it boosts deep hydration, plumps skin and reduces dull, tight-looking skin. Skin regains radiance and long-lasting hydration.',
    ingredients: 'Aqua (Water), Glycerin, Sodium hyaluronate, Panthenol, Tremella fuciformis sporocarp extract, Niacinamide, Allantoin, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply anti-thirst serum on clean face morning and/or evening. Massage gently until fully absorbed. Follow with your regular moisturizer.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/SerumAnti-Soif.png',
    productLink: 'https://seasonly.fr/collections/shop/products/serum-visage-hydratant-anti-soif',
    category: 'Serums',
  },
  {
    id: 'product-15',
    title: 'Anti-Dullness Peeling Mask',
    subtitle: 'AHA facial peeling mask',
    description: 'Seasonly Anti-Dullness Peeling Mask is a mask enriched with AHAs (fruit acids) that deeply exfoliates, fades spots, evens complexion and restores radiance to dull and tired skin. Its innovative formula combines glycolic and lactic acid for an effective and well-tolerated peeling effect.',
    ingredients: 'Aqua (Water), Glycolic acid, Lactic acid, Glycerin, Aloe barbadensis leaf juice, Niacinamide, Sodium hydroxide, Panthenol, Allantoin, Sodium benzoate, Potassium sorbate, Parfum (Fragrance)',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply the mask on clean, dry face in an even layer. Leave on for a maximum of 10 minutes. Rinse thoroughly with warm water. Use 1 to 2 times a week. Do not use on irritated or damaged skin. Apply sun protection SPF 30+ the following day.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/MasquePeeling_7be3dac5-a484-4ffe-ba02-6b31c41e1ff8.png',
    productLink: 'https://seasonly.fr/collections/shop/products/masque-peeling-anti-grisaille',
    category: 'Masks',
  },
  {
    id: 'product-16',
    title: 'Quartz Roller',
    subtitle: 'Facial massage accessory',
    description: 'Seasonly Quartz Roller is an authentic double-headed rose quartz roller. It drains, depuffs and massages the face to reduce swelling, improve circulation and enhance product absorption. The large end for the face, the small end for the eye contour.',
    ingredients: 'N/A - Accessoire en quartz rose naturel',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil or serum on the face. Use the large end of the roller for the face and the small end for the eye contour. Perform upward movements from inside to outside. Clean the roller after each use.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/RollerQuartz_279635b5-f742-4353-b5d8-5f3e5cccf5da.png',
    productLink: 'https://seasonly.fr/collections/shop/products/quartz-roller',
    category: 'Accessories',
  },
  {
    id: 'product-17',
    title: 'Every Season Oil',
    subtitle: 'Multi-use body and hair oil',
    description: 'Seasonly Every Season Oil is a multi-use oil for body and hair. Its formula enriched with precious oils (argan, jojoba, sweet almond) nourishes, hydrates and brings radiance to skin and shine to hair. One product to enhance face, body and hair in all seasons.',
    ingredients: 'Argania spinosa kernel oil, Simmondsia chinensis (Jojoba) seed oil, Prunus amygdalus dulcis (Sweet almond) oil, Tocopherol, Parfum (Fragrance), Limonene, Linalool',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops on body, face or hair by massaging in. For face: 2 to 3 drops morning and/or evening. For body: apply after shower on damp skin. For hair: a few drops as a finishing serum or hair mask.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/EverySeasonOil_27a1f080-613c-4a0b-9b63-1251557dea9c.png',
    productLink: 'https://seasonly.fr/collections/shop/products/every-season-oil',
    category: 'Oils',
  },
  {
    id: 'product-18',
    title: 'Face Boulado',
    subtitle: 'Facial massage accessory',
    description: 'Seasonly Face Boulado is a massage accessory inspired by ancestral techniques. Its round shape and small beads deeply massage the face, stimulate microcirculation, drain toxins and depuff the features. Ideal for a daily facial gym ritual.',
    ingredients: 'N/A - Accessoire de massage',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil on the face. Use the Boulado with circular movements across the entire face. Focus on tension zones (jaw, temples, forehead). Use 2 to 3 minutes each day for visible results.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/Boulado_844bf192-462a-4f5e-b2b3-512299ce034d.png',
    productLink: 'https://seasonly.fr/collections/shop/products/boulado',
    category: 'Accessories',
  },
  {
    id: 'product-19',
    title: 'Rehydrating Mask',
    subtitle: 'Hyaluronic acid mask',
    description: 'Seasonly Rehydrating Mask is an intensive mask enriched with multi-molecular hyaluronic acid that boosts hydration, repairs the skin barrier and leaves skin bouncy and comfortable. Ideal for dry, dehydrated skin or after sun exposure.',
    ingredients: 'Aqua (Water), Glycerin, Sodium hyaluronate, Panthenol, Aloe barbadensis leaf juice, Centella asiatica extract, Allantoin, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a generous layer on clean face. Leave on for 15 to 20 minutes. Rinse or massage the excess until fully absorbed. Use 2 to 3 times a week.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/Masque_Rehydratant_Seasonly.png',
    productLink: 'https://seasonly.fr/collections/shop/products/masque-rehydratant',
    category: 'Masks',
  },
  {
    id: 'product-20',
    title: 'Hydrating Mist',
    subtitle: 'Prebiotic hydrating mist',
    description: 'Seasonly Hydrating Mist is a prebiotic face mist that hydrates, sets makeup and refreshes skin throughout the day. Its lightweight formula strengthens the skin microbiome, soothes redness and maintains optimal hydration. Use at any time of the day.',
    ingredients: 'Aqua (Water), Glycerin, Inulin, Sodium hyaluronate, Niacinamide, Panthenol, Allantoin, Sodium benzoate, Citric acid',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Spray at a distance of 20cm from the face, with eyes closed. Can be used on bare skin, over serum or to set makeup. Use several times a day as needed.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BrumeHydratante.png',
    productLink: 'https://seasonly.fr/collections/shop/products/brume-hydratante',
    category: 'Accessories',
  },
  {
    id: 'product-21',
    title: 'Healthy Glow Cream',
    subtitle: 'Apricot face cream',
    description: 'Out of Stock. Seasonly Healthy Glow Cream is a lightweight cream enriched with apricot oil that brings luminosity and a natural healthy glow. Its formula nourishes, hydrates and evens complexion while giving skin a healthy, radiant look. Ideal for dull skin lacking radiance.',
    ingredients: 'Aqua (Water), Prunus armeniaca (Apricot) kernel oil, Glycerin, Cetearyl alcohol, Niacinamide, Beta-carotene, Tocopherol, Parfum (Fragrance), Sodium benzoate, Citric acid',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply morning and/or evening on clean face. Massage gently until fully absorbed.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/CremeBonneMine.png',
    productLink: 'https://seasonly.fr/collections/shop/products/creme-abricot',
    category: 'Creams',
  },
  {
    id: 'product-22',
    title: 'Jade Gua Sha',
    subtitle: 'Jade massage accessory',
    description: 'Out of Stock. Seasonly Jade Gua Sha is a massage tool crafted from genuine jade. It is used to drain, firm and tone face and body. Naturally cool jade helps depuff, reduce swelling and improve blood circulation.',
    ingredients: 'N/A - Accessoire en jade naturel',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil on the skin. Use the jade gua sha with upward draining movements. For face: follow the natural lines of the face. Clean after each use.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/GuaShaJade_39c7fb0b-67e1-44f2-90b5-095161d02648.png',
    productLink: 'https://seasonly.fr/collections/shop/products/jade-gua-sha',
    category: 'Accessories',
  },
  {
    id: 'product-23',
    title: 'Jade Roller',
    subtitle: 'Depuffing massage accessory',
    description: 'Seasonly Jade Roller is a double-headed jade roller for facial massage. Its naturally cold stone depuffs, reduces bags and swelling, and enhances product absorption. Ideal in a morning routine for an immediate depuffed effect.',
    ingredients: 'N/A - Accessoire en jade naturel',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of serum or oil on the face. Use the jade roller with upward and inside-to-outside movements. Large end for the face, small end for the eye contour. Clean the roller after each use.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/RollerJade_a0f96411-cfea-4c9b-8e1a-9042dbd979f0.png',
    productLink: 'https://seasonly.fr/collections/shop/products/jade-roller',
    category: 'Accessories',
  },
  {
    id: 'product-24',
    title: 'Sensitive Skin Night Oil',
    subtitle: 'Repairing fragrance-free face oil',
    description: 'Out of Stock. Seasonly Sensitive Skin Night Oil is the fragrance-free version of the Night Oil. Formulated for sensitive and reactive skin, it repairs, nourishes and regenerates skin during sleep without risk of irritation. Its 100% natural formula is enriched with bakuchiol and rose hip oil.',
    ingredients: 'Rosa canina fruit oil, Argania spinosa kernel oil, Squalane, Helichrysum italicum flower extract, Bakuchiol, Tocopherol',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply 3 to 5 drops in the evening on clean face and neck. Massage until fully absorbed. Ideal combined with a gua sha to amplify effects.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/HuiledeNuit15mlSensible.png',
    productLink: 'https://seasonly.fr/collections/shop/products/huile-de-nuit-sans-parfum',
    category: 'Oils',
  },
  {
    id: 'product-25',
    title: 'De-Puffing Eye Serum Refill',
    subtitle: 'Anti-dark circle eye contour serum',
    description: 'The Seasonly De-Puffing Eye Serum Refill lets you refill your original bottle in an eco-responsible way. Same formula enriched with caffeine, peptides and hyaluronic acid to reduce dark circles, bags and fine lines. A sustainable beauty gesture for continued eye care.',
    ingredients: 'Aqua (Water), Glycerin, Niacinamide, Caffeine, Sodium hyaluronate, Panthenol, Acetyl tetrapeptide-5, Tocopherol, Allantoin, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Fill the original bottle with the refill. Apply morning and evening on clean eye contour. Pat gently until fully absorbed.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/serum-regard-recharge-300dpi.png',
    productLink: 'https://seasonly.fr/collections/shop/products/recharge-serum-regard-defatigant',
    category: 'Serums',
  },
  {
    id: 'product-26',
    title: 'De-Puffing Eye Serum Duo',
    subtitle: 'Anti-dark circle eye contour serum',
    description: 'Save €12. The De-Puffing Eye Serum Duo includes the Eye Serum and its refill. Benefit from a great price while adopting an eco-responsible approach. The formula enriched with caffeine, peptides and hyaluronic acid reduces dark circles, depuffs bags and smooths fine lines.',
    ingredients: 'Aqua (Water), Glycerin, Niacinamide, Caffeine, Sodium hyaluronate, Panthenol, Acetyl tetrapeptide-5, Tocopherol, Allantoin, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply serum morning and evening on clean eye contour. Pat gently until fully absorbed. Avoid direct contact with eyes.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleSerumregard_Rechargeserumregard.png',
    productLink: 'https://seasonly.fr/collections/shop/products/duo-serum-regard-defatigant-1',
    category: 'Serums',
  },
  {
    id: 'product-27',
    title: 'Massage Ball',
    subtitle: 'Gym massage ball',
    description: 'Seasonly Massage Ball is a facial gym accessory that works deep into face and neck muscles. Used in self-massage, it stimulates blood circulation, relaxes muscle tension and improves facial contour. Available in black (orange).',
    ingredients: 'N/A - Accessoire de massage',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil on the face. Use the massage ball with circular movements on cheeks, forehead and jaw. Focus on tension zones. Use a few minutes each day.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BalleMassageNoire.png',
    productLink: 'https://seasonly.fr/collections/shop/products/balle-de-massage',
    category: 'Skincare',
  },
  {
    id: 'product-28',
    title: 'Multi-Head Roller',
    subtitle: 'Facial massage accessory',
    description: 'Seasonly Multi-Head Roller is a 3-in-1 accessory featuring a gua sha, an obsidian roller and a boulado. This versatile tool adapts to all massage needs: drainage, firming, muscle relaxation. Perfect for a complete facial gym routine.',
    ingredients: 'N/A - Accessoire de massage multi-têtes',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Choose the head suited to your current need. Apply an oil or serum on the face. Use the multi-head roller with movements adapted to each technique (gua sha, roller, boulado). Refer to tutorials available on the website.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/RollerMultiTetes.png',
    productLink: 'https://seasonly.fr/collections/shop/products/roller-multi-tetes',
    category: 'Accessories',
  },
  {
    id: 'product-29',
    title: 'Duo Jade Mushrooms',
    subtitle: 'Jade massage accessories',
    description: 'Seasonly Duo Jade Mushrooms consists of two genuine jade massage mushrooms. Inspired by Asian massage techniques, this accessory allows you to sculpt, drain and tone the face. The mushroom shape perfectly adapts to facial curves for precise and effective massage.',
    ingredients: 'N/A - Accessoire en jade naturel',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply an oil on the face. Use the jade mushrooms with gliding and pressing movements on areas to work. Ideal for cheeks, forehead and neck. Clean after each use.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/MushroomsJade.png',
    productLink: 'https://seasonly.fr/collections/shop/products/jade-mushrooms',
    category: 'Skincare',
  },
  {
    id: 'product-30',
    title: 'Opal Gua Sha',
    subtitle: 'Opal facial massage accessory',
    description: 'Seasonly Opal Gua Sha is a massage tool crafted from opal. Its ergonomic shape facilitates handling and allows precise facial massage. Ideal for beginners in gua sha, it drains, firms and depuffs effectively.',
    ingredients: 'N/A - Accessoire en opale naturelle',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil on the face. Use the opal gua sha with drainage movements from the center outward. Perform 5 to 10 passes per zone. Clean after each use.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/GUASHAOPALE.png',
    productLink: 'https://seasonly.fr/collections/shop/products/opale-gua-sha',
    category: 'Accessories',
  },
  {
    id: 'product-31',
    title: 'C-Activ+ Serum',
    subtitle: 'Anti-spot radiance booster serum',
    description: 'New. Seasonly C-Activ+ Serum is a stabilized, high-concentration Vitamin C serum that targets pigmentation spots, evens complexion and boosts radiance. Its innovative formula combines 15% Vitamin C with niacinamide and antioxidant actives for a luminous, even complexion. Result: -30% spots after 4 weeks of use.',
    ingredients: 'Aqua (Water), Ascorbyl glucoside, Glycerin, Niacinamide, Propanediol, Sodium hyaluronate, Ferulic acid, Tocopherol, Panthenol, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply C-Activ+ serum on clean face, preferably in the morning. Apply 3 to 4 drops and massage until absorbed. Mandatory: follow with SPF 30+ sun protection in the morning. Can be used daily.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/Serum_C-Activ.png',
    productLink: 'https://seasonly.fr/collections/shop/products/serum-c-activ-1',
    category: 'Serums',
  },
  {
    id: 'product-32',
    title: 'Reflexology Tool Seasonly x Face Soul Yoga',
    subtitle: 'Facial reflexology accessory',
    description: 'Seasonly x Face Soul Yoga Reflexology Tool is a facial reflexology accessory co-created with Face Soul Yoga. It stimulates facial reflexology points to relieve tension, improve circulation and optimize product effectiveness. A unique accessory for a holistic approach to facial care.',
    ingredients: 'N/A - Accessoire de réflexologie faciale',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil on the face. Use the reflexology tool following the usage protocol included in the packaging. Stimulate each reflexology point with light circular pressures. Use 5 to 10 minutes per day.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/Reflexo.png',
    productLink: 'https://seasonly.fr/collections/shop/products/tool-de-reflexologie',
    category: 'Skincare',
  },
  {
    id: 'product-33',
    title: 'Ceramic Gua Sha',
    subtitle: 'Facial massage accessory',
    description: 'Seasonly Ceramic Gua Sha is a massage tool crafted from high-quality ceramic. Its smooth, cool surface allows gliding and effective facial massage. It drains, firms, depuffs and improves skin radiance.',
    ingredients: 'N/A - Accessoire en céramique',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply a few drops of oil on the face. Use the ceramic gua sha following the natural lines of the face. Perform upward movements with light pressure. Clean after each use.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/GuaShaCeramique.png',
    productLink: 'https://seasonly.fr/collections/shop/products/gua-sha-ceramique',
    category: 'Accessories',
  },
  {
    id: 'product-34',
    title: 'Double Cleanse Duo',
    subtitle: 'Double facial cleansing duo',
    description: 'Save €12. Seasonly Double Cleanse Duo combines the Cleansing Oil and the Cleansing Gel for complete two-step cleansing. The first oil step dissolves makeup and impurities. The second gel step purifies and soothes skin. Result: perfectly clean, clear and comfortable skin.',
    ingredients: 'Voir chaque produit séparément : Huile Démaquillante + Gelée Nettoyante Visage',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Step 1: Apply Cleansing Oil on dry skin, massage and rinse. Step 2: Apply Cleansing Gel on damp skin, massage and rinse. Use morning and/or evening.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleHuiledemaquillante_Geleenettoyante.png',
    productLink: 'https://seasonly.fr/collections/shop/products/duo-double-nettoyage',
    category: 'Skincare',
  },
  {
    id: 'product-35',
    title: 'Radiance Routine',
    subtitle: 'Radiance complexion routine set',
    description: 'Save €32. Seasonly Radiance Routine is a complete set for a luminous, even complexion. It combines the C-Activ+ Serum (anti-spot, radiance booster) and the Night Oil (repairing) for a complete morning/evening routine effective against spots and dull complexion.',
    ingredients: 'Voir chaque produit séparément : Sérum C-Activ+ + Huile de Nuit',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Morning: Apply C-Activ+ Serum on clean face, follow with sun protection. Evening: Apply Night Oil on clean face, massage until absorbed.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/Bundleroutineeclat_8155dbf1-e4e9-43c6-9131-73e92afef363.png',
    productLink: 'https://seasonly.fr/collections/shop/products/routine-eclat',
    category: 'Skincare',
  },
  {
    id: 'product-36',
    title: 'Notox Duo Cream + TensioLift Oil',
    subtitle: 'Expert anti-spot and firming duo',
    description: 'Save €31. Notox Duo Cream + TensioLift Oil combines the TensioLift Day Cream and TensioLift Oil for a complete anti-aging and anti-spot routine. A synergy of lifting actives for clinically proven results on wrinkles and spots.',
    ingredients: 'Voir chaque produit séparément : Crème de Jour TensioLift + Huile TensioLift',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Morning: Apply TensioLift Day Cream on clean face. Evening: Apply TensioLift Oil by massaging following the self-massage protocol.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleNOTOX-03_c75e70ac-64e2-4ad4-bd22-fa84b0eaca9c.png',
    productLink: 'https://seasonly.fr/collections/shop/products/duo-notox-creme-huile-tensiolift',
    category: 'Oils',
  },
  {
    id: 'product-37',
    title: 'Notox Duo Serum + TensioLift Oil',
    subtitle: 'Expert anti-aging and firming duo',
    description: 'Notox Duo Serum + TensioLift Oil combines the TensioLift Serum and TensioLift Oil for a double lifting and anti-aging action. This duo concentrated in Argireline® and Spilanthes acts on wrinkles, fine lines and skin firmness. Clinically proven effective from 28 days.',
    ingredients: 'Voir chaque produit séparément : Sérum TensioLift + Huile TensioLift',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply TensioLift Serum on clean face, then TensioLift Oil on top. Massage following the self-massage protocol sent by email. Use morning and/or evening.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleNOTOX_Plandetravail1_2ea5b491-e6a8-410f-b9b0-f82d8741129b.png',
    productLink: 'https://seasonly.fr/collections/shop/products/bundle-notox-serum-huile-tensiolift',
    category: 'Serums',
  },
  {
    id: 'product-38',
    title: 'Notox Duo Serum + TensioLift Cream',
    subtitle: 'Expert anti-aging and anti-spot duo',
    description: 'Save €33. Notox Duo Serum + TensioLift Cream combines the TensioLift Serum and TensioLift Day Cream for a complete anti-aging and anti-spot routine. The synergy of Argireline®, Matrixyl® and anti-spot actives delivers clinically proven results.',
    ingredients: 'Voir chaque produit séparément : Sérum TensioLift + Crème de Jour TensioLift',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Morning: Apply TensioLift Serum then TensioLift Day Cream. Evening: Apply TensioLift Serum alone or with Night Oil.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleNOTOX-02_08676079-17da-432f-a666-3bbcd1e709cc.png',
    productLink: 'https://seasonly.fr/collections/shop/products/bundle-notox-serum-creme-tensiolift',
    category: 'Serums',
  },
  {
    id: 'product-39',
    title: 'Notox Routine Serum + Cream + TensioLift Oil',
    subtitle: 'Complete TensioLift anti-aging routine',
    description: 'Seasonly Notox Routine brings together the 3 hero products from the TensioLift range: TensioLift Serum, TensioLift Day Cream and TensioLift Oil. A complete, clinically proven program to smooth wrinkles, firm and even complexion.',
    ingredients: 'Voir chaque produit séparément : Sérum TensioLift + Crème de Jour TensioLift + Huile TensioLift',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Morning: TensioLift Serum + TensioLift Day Cream. Evening: TensioLift Serum + TensioLift Oil massaging following the protocol.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleNOTOX-04.png',
    productLink: 'https://seasonly.fr/collections/shop/products/bundle-notox',
    category: 'Serums',
  },
  {
    id: 'product-40',
    title: 'Summer Boost Trio',
    subtitle: 'Summer healthy glow set',
    description: 'Seasonly Summer Boost Trio is the ideal summer set combining Tan Boost Oil, New Skin Mask and a massage accessory. A complete trio to prepare, enhance and maintain your skin during summer season.',
    ingredients: 'Voir chaque produit séparément',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'See each product separately for usage instructions.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleTanBoost_Plandetravail1_1.png',
    productLink: 'https://seasonly.fr/collections/shop/products/summer-boost-trio',
    category: 'Skincare',
  },
  {
    id: 'product-41',
    title: '21-Day Challenge Duo',
    subtitle: 'Introductory facial massage duo',
    description: 'Seasonly 21-Day Challenge Duo combines Anti-Thirst Serum and Night Oil to start a 21-day self-massage program. This duo guides beginners into facial massage with suitable products and a guided protocol. In 21 days, adopt the ritual that will transform your skin.',
    ingredients: 'Voir chaque produit séparément : Sérum Anti-Soif + Huile de Nuit',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Follow the 21-day self-massage program sent by email at purchase. Apply Anti-Thirst Serum morning and evening, Night Oil in the evening by massaging.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleSerumanti-soif_Huiledenuit.png',
    productLink: 'https://seasonly.fr/collections/shop/products/duo-complement-21-day-challenge',
    category: 'Skincare',
  },
  {
    id: 'product-42',
    title: 'Skin Cycling Routine',
    subtitle: 'Complexion radiance routine',
    description: 'Seasonly Skin Cycling Routine is a 4-product routine inspired by the skin cycling trend to detoxify and regenerate skin. By alternating active treatments (exfoliation, repair) over 4 days, this routine optimizes results and avoids overexposure to actives. A complete program for transformed skin.',
    ingredients: 'Voir chaque produit séparément',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Day 1: Exfoliation (Anti-Dullness Peeling Mask). Day 2: Retinol (Night Oil with bakuchiol). Days 3 & 4: Recovery (hydrating serum + nourishing cream). Repeat the cycle.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/SKINCYCLING.png',
    productLink: 'https://seasonly.fr/collections/shop/products/routine-skin-cycling',
    category: 'Skincare',
  },
  {
    id: 'product-43',
    title: '21-Day Challenge',
    subtitle: 'Give your face a workout',
    description: 'Seasonly 21-Day Challenge is a complete 21-day facial self-massage program. It includes Anti-Thirst Serum, Night Oil and Quartz Gua Sha, plus a guided self-massage protocol. In 21 days, discover the benefits of facial massage: radiant complexion, firmed features, relaxed skin.',
    ingredients: 'Voir chaque produit séparément : Sérum Anti-Soif + Huile de Nuit + Gua Sha Quartz',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Follow the 21-day self-massage protocol sent by email at purchase. Use included products daily following instructions.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleSerumanti-soif_Huiledenuit_Guashaquartz.png',
    productLink: 'https://seasonly.fr/collections/shop/products/21-day-challenge',
    category: 'Skincare',
  },
  {
    id: 'product-44',
    title: 'Roll & Plump',
    subtitle: 'Facial massage duo',
    description: 'Save €15. Roll & Plump is the perfect facial massage ritual duo: Night Oil and Jade Roller. The oil nourishes and repairs during the night while the jade roller drains and depuffs. A complementary duo for replumped, depuffed skin at wake-up.',
    ingredients: 'Voir chaque produit séparément : Huile de Nuit + Jade Roller',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Evening: Apply Night Oil on the face. Use the Jade Roller to absorb the oil and drain the face. Perform upward movements for 5 minutes.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleHuiledenuit_Rollerjade.png',
    productLink: 'https://seasonly.fr/collections/shop/products/hdn-jade-roller',
    category: 'Skincare',
  },
  {
    id: 'product-45',
    title: 'Orange Cleansing Trio',
    subtitle: 'Facial cleansing set',
    description: 'Seasonly Orange Cleansing Trio is a complete cleansing set including the essentials for an effective cleansing routine. It includes Cleansing Oil, Cleansing Gel and a cleansing accessory. An ideal trio for daily skin care.',
    ingredients: 'Voir chaque produit séparément',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'See each product separately for usage instructions.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/trio-nettoyage-orange-pack-seasonly-794666.png',
    productLink: 'https://seasonly.fr/collections/shop/products/trio-nettoyage',
    category: 'Cleansers',
  },
  {
    id: 'product-46',
    title: 'Lift & Wake Up',
    subtitle: 'Gua Sha and Night Oil 30ml Duo',
    description: 'Save €19. Lift & Wake Up combines Night Oil 30ml and Quartz Gua Sha for a lifting and repairing night ritual. Night Oil repairs and regenerates during sleep, Quartz Gua Sha drains and firms the face. In the morning, skin is replumped, features are defined and radiance is restored.',
    ingredients: 'Voir chaque produit séparément : Huile de Nuit 30ml + Gua Sha Quartz',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Evening: Apply Night Oil on clean face. Massage with the Quartz Gua Sha following lymphatic drainage directions. Perform the ritual for 5 to 10 minutes.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleHuiledenuit_Guashaquartz.png',
    productLink: 'https://seasonly.fr/collections/shop/products/lift-wake-up-30ml',
    category: 'Skincare',
  },
  {
    id: 'product-47',
    title: 'Body Sculpt Duo',
    subtitle: 'Expert firming body duo',
    description: 'Save €14. Seasonly Body Sculpt Duo combines Every Season Oil and Quartz Gua Sha for a body firming ritual. The multi-use oil nourishes and enhances skin, the gua sha drains and sculpts contours. A complete duo for firm, nourished and radiant skin.',
    ingredients: 'Voir chaque produit séparément : Every Season Oil + Gua Sha Quartz',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply Every Season Oil on the body. Use the Quartz Gua Sha to drain and sculpt areas to work on. Perform upward and draining movements.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleEvery-seasonoil_Guashaquartz.png',
    productLink: 'https://seasonly.fr/collections/shop/products/duo-body-sculpt',
    category: 'Skincare',
  },
  {
    id: 'product-48',
    title: 'Inner Glow Duo',
    subtitle: 'Facial radiance duo',
    description: 'Save €13. Seasonly Inner Glow Duo combines the Anti-Dullness Peeling Mask and the Cleansing Gel for a complete radiance routine. The peel exfoliates and tightens pores, the gel gently cleanses. Result: radiant, even and purified complexion.',
    ingredients: 'Voir chaque produit séparément : Masque Peeling Anti-Grisaille + Gelée Nettoyante Visage',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: '1 to 2 times a week: Use Cleansing Gel to clean face, then apply Anti-Dullness Peeling Mask for 10 minutes, rinse.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleMasquepeeling_Geleenettoyante.png',
    productLink: 'https://seasonly.fr/collections/shop/products/duo-nouveautes-inner-glow',
    category: 'Skincare',
  },
  {
    id: 'product-49',
    title: 'Night Reset',
    subtitle: 'Repairing night routine',
    description: 'Save €18. Seasonly Night Reset is a complete night routine including Cleansing Oil, Fluid Cream and Night Oil. A 3-step routine to cleanse, hydrate and repair skin during sleep. In the morning, skin is clean, nourished and radiant.',
    ingredients: 'Voir chaque produit séparément : Huile Démaquillante + Crème Fluide + Huile de Nuit',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Step 1: Remove makeup with Cleansing Oil. Step 2: Hydrate with Fluid Cream. Step 3: Repair with Night Oil.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleHuiledemaquillante_Cremefluide_Huiledenuit.png',
    productLink: 'https://seasonly.fr/collections/shop/products/night-reset-routine-de-nuit',
    category: 'Skincare',
  },
  {
    id: 'product-50',
    title: 'Summer Boost',
    subtitle: 'Summer healthy glow set',
    description: 'Seasonly Summer Boost is a summer set including Tan Boost Oil and a massage accessory. Ideal for preparing and enhancing skin for summer, with a natural sun-kissed effect.',
    ingredients: 'Voir chaque produit séparément',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'See each product separately for usage instructions.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleTanBoost_Plandetravail1_1.png',
    productLink: 'https://seasonly.fr/collections/shop/products/summer-boost-4',
    category: 'Skincare',
  },
  {
    id: 'product-51',
    title: 'Summer Boost with New Skin Mask',
    subtitle: 'Summer healthy glow set with mask',
    description: 'Seasonly Summer Boost with New Skin Mask is a summer set including Tan Boost Oil and New Skin Mask. The mask exfoliates and smooths skin before applying the healthy glow oil for natural, radiant results.',
    ingredients: 'Voir chaque produit séparément : Huile Tan Boost + Masque Peau Neuve',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Use New Skin Mask 1 to 2 times a week to exfoliate. Apply Tan Boost Oil on clean skin for a healthy glow effect.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleTanBoost-02.png',
    productLink: 'https://seasonly.fr/collections/shop/products/summer-boost-avec-masque-peau-neuve',
    category: 'Masks',
  },
  {
    id: 'product-52',
    title: 'Night Reset with Jade Gua Sha',
    subtitle: 'Facial lymphatic drainage routine',
    description: 'Out of Stock. Night Reset with Jade Gua Sha is the complete Seasonly night routine with the addition of the Jade Gua Sha. A repairing night routine enhanced with a lymphatic drainage ritual for even more transformed skin at wake-up.',
    ingredients: 'Voir chaque produit séparément : Huile Démaquillante + Crème Fluide + Huile de Nuit + Jade Gua Sha',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Follow the Night Reset routine and add the Jade Gua Sha before applying Night Oil for optimal lymphatic drainage.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleHuiledemaquillante_Cremefluide_Huiledenuit.png',
    productLink: 'https://seasonly.fr/collections/shop/products/night-reset-avec-gua-sha-jade',
    category: 'Accessories',
  },
  {
    id: 'product-53',
    title: 'Night Reset with Mushroom Quartz',
    subtitle: 'Facial lymphatic drainage routine',
    description: 'Seasonly Night Reset with Mushroom Quartz is the complete night routine enriched with Duo Jade Mushrooms. A night ritual to cleanse, hydrate, massage with mushrooms and repair skin during sleep.',
    ingredients: 'Voir chaque produit séparément : Huile Démaquillante + Crème Fluide + Huile de Nuit + Duo Jade Mushrooms',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Follow the Night Reset routine and integrate massage with Jade Mushrooms for lymphatic drainage and facial sculpting.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleHuiledemaquillante_Cremefluide_Huiledenuit.png',
    productLink: 'https://seasonly.fr/collections/shop/products/night-reset-avec-mushroom-quartz',
    category: 'Skincare',
  },
  {
    id: 'product-54',
    title: 'Night Reset with Ceramic Gua Sha',
    subtitle: 'Facial lymphatic drainage routine',
    description: 'Seasonly Night Reset with Ceramic Gua Sha is the complete night routine enriched with the Ceramic Gua Sha. The ceramic gua sha offers a smoothing and draining massage to amplify the repairing effects of the night routine.',
    ingredients: 'Voir chaque produit séparément : Huile Démaquillante + Crème Fluide + Huile de Nuit + Gua Sha Céramique',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Follow the Night Reset routine and use the Ceramic Gua Sha to massage and drain the face before applying Night Oil.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/BundleHuiledemaquillante_Cremefluide_Huiledenuit.png',
    productLink: 'https://seasonly.fr/collections/shop/products/night-reset-avec-gua-sha-ceramique',
    category: 'Accessories',
  },
  {
    id: 'product-55',
    title: 'TensioLift Eye & Lip Cream',
    subtitle: '1st care with \'FACE TAPING\' effect',
    description: 'Seasonly TensioLift Eye & Lip Cream is the first care with a \'FACE TAPING\' effect. Enriched with Argireline® and lifting actives, it simultaneously targets the eye contour and lip contour to smooth, firm and replump these delicate areas. One care to treat both areas most revealing of age.',
    ingredients: 'Aqua (Water), Glycerin, Caprylic/capric triglyceride, Cetearyl alcohol, Acetyl hexapeptide-8, Sodium hyaluronate, Niacinamide, Caffeine, Tocopherol, Allantoin, Carbomer, Sodium hydroxide, Phenoxyethanol, Ethylhexylglycerin',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply the cream morning and evening on the eye contour and lip contour. Pat gently with ring finger until fully absorbed. Can be used alone or under makeup.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/SEASONLY_TL_PACK.png',
    productLink: 'https://seasonly.fr/collections/shop/products/creme-yeux-levres-tensiolift',
    category: 'Creams',
  },
  {
    id: 'product-56',
    title: 'Sculpt Routine',
    subtitle: 'Anti-aging sculpting routine',
    description: 'Save €39. Seasonly Sculpt Routine is a complete routine combining TensioLift Day Cream, Boulado and a massage accessory. An ideal combination to sculpt, firm and lift facial features daily.',
    ingredients: 'Voir chaque produit séparément',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Morning: Apply TensioLift Day Cream. Use the Boulado to massage and activate the cream. Perform the massage ritual daily.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/2025.11.19-NLblackfriday_desktop4biscopie5.jpg',
    productLink: 'https://seasonly.fr/collections/shop/products/routine-sculpt',
    category: 'Skincare',
  },
  {
    id: 'product-57',
    title: 'Glow Routine',
    subtitle: 'Radiance complexion routine',
    description: 'Save €23. Seasonly Glow Routine is a healthy glow routine combining Tan Boost Oil and New Skin Mask for a tanned and radiant complexion. Exfoliate with the mask then apply the healthy glow oil for natural, luminous results.',
    ingredients: 'Voir chaque produit séparément : Huile Tan Boost + Masque Peau Neuve',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: '1 to 2 times a week: Apply New Skin Mask to exfoliate. Daily: Apply Tan Boost Oil for a healthy glow effect.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/2025.11.19-NLblackfriday_desktop4biscopie2.jpg',
    productLink: 'https://seasonly.fr/collections/shop/products/routine-glow',
    category: 'Skincare',
  },
  {
    id: 'product-58',
    title: 'RIISE x SEASONLY',
    subtitle: 'The Holiday Pack',
    description: 'New. RIISE x SEASONLY Holiday Pack is an exclusive collaboration between Seasonly and RIISE. This holiday set brings together selected products for a complete and festive skincare ritual. A perfect gift for the holidays.',
    ingredients: 'Voir chaque produit séparément inclus dans le coffret',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'See each product separately for usage instructions.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/RIISExSeasonly-site-header.jpg',
    productLink: 'https://seasonly.fr/collections/shop/products/le-pack-des-fetes-riise-x-seasonly',
    category: 'Skincare',
  },
  {
    id: 'product-59',
    title: 'Night Oil 5ml',
    subtitle: 'Repairing face oil',
    description: 'The Night Oil in 5ml format is the travel and discovery size of the Seasonly Best Seller Night Oil. Ideal for travel, testing the product or gifting. Its 100% natural formula enriched with bakuchiol and rose hip oil repairs and regenerates skin during sleep.',
    ingredients: 'Rosa canina fruit oil, Argania spinosa kernel oil, Squalane, Helichrysum italicum flower extract, Bakuchiol, Tocopherol, Parfum (Fragrance), Limonene, Linalool, Geraniol, Citronellol',
    delivery: 'Home delivery Colissimo with signature: €5 for orders under €69 | Pickup point Mondial Relay: €4 for orders under €69 | Express home delivery Chronopost: €11',
    howToUse: 'Apply 2 to 3 drops in the evening on clean face and neck. Massage until fully absorbed.',
    imageUrl: 'https://seasonly.fr/cdn/shop/files/HuiledeNuit5ml.png',
    productLink: 'https://seasonly.fr/collections/shop/products/mini-huile-de-nuit',
    category: 'Oils',
  },
];

export const productCategories = ['All', ...Array.from(new Set(products.map(p => p.category)))];