export interface Tip {
  id: string;
  titleEn: string;
  titleFr: string;
  bodyEn: string;
  bodyFr: string;
  stepsEn: string[];
  stepsFr: string[];
  category: string;
  readMinutes: number;
  points: number;
}

export const tips: Tip[] = [
  {
    id: '1',
    titleEn: 'Morning Hydration Ritual',
    titleFr: "Rituel d'hydratation du matin",
    bodyEn: 'Start your day with this simple yet powerful hydration ritual. Apply your serum on damp skin to lock in moisture, then follow with a lightweight cream.',
    bodyFr: "Commencez votre journée avec ce rituel d'hydratation puissant. Appliquez votre sérum sur une peau humide pour fixer l'humidité, puis suivez avec une crème légère.",
    stepsEn: [
      'Splash your face with lukewarm water — leave skin slightly damp',
      'Apply 2–3 drops of serum to damp skin, pressing gently into face',
      'Wait 60 seconds for the serum to fully absorb',
      'Apply a pea-sized amount of lightweight moisturizer',
      'Massage upward in circular motions for 1 minute to boost circulation',
      'Finish with SPF 30+ as the last step of your morning routine',
    ],
    stepsFr: [
      "Rincez votre visage à l'eau tiède — laissez la peau légèrement humide",
      "Appliquez 2–3 gouttes de sérum sur peau humide en pressant doucement",
      "Attendez 60 secondes pour que le sérum soit bien absorbé",
      "Appliquez une noisette de crème légère",
      "Massez vers le haut en mouvements circulaires pendant 1 minute",
      "Terminez avec un SPF 30+ comme dernière étape de votre routine matinale",
    ],
    category: 'Routine',
    readMinutes: 2,
    points: 10,
  },
  {
    id: '2',
    titleEn: 'The Power of Vitamin C for Radiance',
    titleFr: "Le pouvoir de la vitamine C pour l'éclat",
    bodyEn: 'Vitamin C neutralizes free radicals, brightens dark spots, and stimulates collagen production. Apply it every morning before SPF for maximum glow.',
    bodyFr: "La vitamine C neutralise les radicaux libres, illumine les taches sombres et stimule la production de collagène. Appliquez-la chaque matin avant l'écran solaire.",
    stepsEn: [
      'Start with a clean, dry face after your morning cleanse',
      'Apply 3–4 drops of Vitamin C serum to your fingertips',
      'Press evenly across face, neck and décolleté — avoid the eye area',
      'Wait 2 minutes for full absorption before applying the next product',
      'Follow with your regular moisturizer',
      'Always finish with SPF 30+ — Vitamin C and SPF amplify each other',
    ],
    stepsFr: [
      "Commencez avec un visage propre et sec après votre nettoyage matinal",
      "Appliquez 3–4 gouttes de sérum vitamine C sur vos doigts",
      "Pressez uniformément sur le visage, le cou et le décolleté",
      "Attendez 2 minutes pour une absorption complète avant d'appliquer le produit suivant",
      "Appliquez votre crème hydratante habituelle",
      "Terminez toujours avec un SPF 30+ — vitamine C et SPF se renforcent mutuellement",
    ],
    category: 'Ingredients',
    readMinutes: 3,
    points: 10,
  },
  {
    id: '3',
    titleEn: 'Facial Massage: The Natural Facelift',
    titleFr: 'Massage facial : le lifting naturel',
    bodyEn: 'Regular facial massage activates 57 facial muscles, boosts lymphatic drainage to reduce puffiness, and increases blood flow for a natural lift. Just 5 minutes daily shows visible results within 2 weeks.',
    bodyFr: "Le massage facial régulier active les 57 muscles du visage, stimule le drainage lymphatique pour réduire les gonflements et augmente la circulation sanguine pour un lifting naturel.",
    stepsEn: [
      'Apply a few drops of facial oil or serum for slip — never massage dry skin',
      'Neck: stroke upward from collarbone to chin, 5× on each side',
      'Jawline: pinch gently along the bone from chin to ear, 5 reps',
      'Cheeks: circular upward strokes with knuckles, 5 circles each side',
      'Under-eye: gentle tapping with ring finger from inner to outer corner, 10 taps',
      'Forehead: smooth outward strokes from centre to temples, 5 strokes',
    ],
    stepsFr: [
      "Appliquez quelques gouttes d'huile ou de sérum — ne massez jamais la peau sèche",
      "Cou : remontez de la clavicule vers le menton, 5× de chaque côté",
      "Mâchoire : pincez doucement le long de l'os du menton à l'oreille, 5 fois",
      "Joues : mouvements circulaires vers le haut avec les jointures, 5 cercles de chaque côté",
      "Contour des yeux : tapotements doux avec l'annulaire de l'intérieur vers l'extérieur, 10 fois",
      "Front : mouvements lissants du centre vers les tempes, 5 fois",
    ],
    category: 'Technique',
    readMinutes: 3,
    points: 10,
  },
  {
    id: '4',
    titleEn: 'Double Cleansing: The Ritual That Changes Everything',
    titleFr: 'Double nettoyage : le rituel qui change tout',
    bodyEn: 'Double cleansing removes all traces of SPF, makeup, and pollution. Your subsequent skincare products will absorb up to 30% better.',
    bodyFr: "Le double nettoyage élimine toutes les traces de protection solaire, maquillage et pollution. Vos soins suivants s'absorberont jusqu'à 30% mieux.",
    stepsEn: [
      'Apply oil-based cleanser to dry skin and massage for 60 seconds',
      'Add a little water to emulsify — the texture will turn milky',
      'Rinse thoroughly with lukewarm water',
      'Apply water-based cleanser to damp skin and massage for 30 seconds',
      'Rinse well and pat dry gently with a clean towel',
      'Apply your toner or serum immediately while skin is still damp',
    ],
    stepsFr: [
      "Appliquez un nettoyant huileux sur peau sèche et massez pendant 60 secondes",
      "Ajoutez un peu d'eau pour émulsionner — la texture deviendra laiteuse",
      "Rincez abondamment à l'eau tiède",
      "Appliquez un nettoyant aqueux sur peau humide et massez 30 secondes",
      "Rincez et tamponnez doucement avec une serviette propre",
      "Appliquez votre tonique ou sérum immédiatement pendant que la peau est encore humide",
    ],
    category: 'Routine',
    readMinutes: 2,
    points: 10,
  },
  {
    id: '5',
    titleEn: 'Hyaluronic Acid: How to Use It Correctly',
    titleFr: "Acide hyaluronique : comment bien l'utiliser",
    bodyEn: 'Hyaluronic acid draws moisture into your skin — but only when applied to damp skin. This one trick triples its effectiveness.',
    bodyFr: "L'acide hyaluronique attire l'humidité vers votre peau — mais uniquement si appliqué sur peau humide. Cette astuce triple son efficacité.",
    stepsEn: [
      'After cleansing, do NOT fully dry your face — leave it damp',
      'Dispense 2–3 drops of HA serum onto fingertips',
      'Press gently across face, neck and chest — do not rub',
      'Hold each area for 5 seconds to help absorption',
      'Immediately apply moisturizer on top to seal in the moisture',
      'Avoid using HA on completely dry skin — it will pull moisture out instead',
    ],
    stepsFr: [
      "Après le nettoyage, ne séchez PAS complètement votre visage — laissez-le humide",
      "Versez 2–3 gouttes de sérum HA sur vos doigts",
      "Pressez doucement sur le visage, le cou et la poitrine — ne frottez pas",
      "Maintenez chaque zone 5 secondes pour favoriser l'absorption",
      "Appliquez immédiatement une crème pour sceller l'humidité",
      "Évitez d'utiliser l'HA sur peau sèche — il extraira l'humidité à la place",
    ],
    category: 'Ingredients',
    readMinutes: 3,
    points: 10,
  },
  {
    id: '6',
    titleEn: 'Collagen & Elastin: Protecting Your Skin Structure',
    titleFr: "Collagène & Élastine : préserver la structure de votre peau",
    bodyEn: 'After 25, your body produces 1% less collagen per year. Build your daily routine around protecting what you have and stimulating production.',
    bodyFr: "Après 25 ans, votre corps produit 1% de collagène en moins par an. Construisez votre routine quotidienne pour protéger ce que vous avez et stimuler la production.",
    stepsEn: [
      'Apply SPF 30–50 every morning as the last step of your AM routine',
      'Use a Vitamin C serum each morning to stimulate collagen synthesis',
      'Add a retinol product to your PM routine, 2–3× per week',
      'Drink at least 8 glasses of water daily to maintain skin plumpness',
      'Do 5 minutes of facial massage to stimulate fibroblast activity',
      'Eat collagen-boosting foods: bone broth, berries, and leafy greens',
    ],
    stepsFr: [
      "Appliquez un SPF 30–50 chaque matin en dernière étape de votre routine",
      "Utilisez un sérum vitamine C chaque matin pour stimuler la synthèse du collagène",
      "Ajoutez un produit rétinol à votre routine PM, 2–3× par semaine",
      "Buvez au moins 8 verres d'eau par jour pour maintenir la plénitude de la peau",
      "Faites 5 minutes de massage facial pour stimuler l'activité des fibroblastes",
      "Mangez des aliments favorisant le collagène : bouillon d'os, baies, légumes verts",
    ],
    category: 'Science',
    readMinutes: 4,
    points: 10,
  },
  {
    id: '7',
    titleEn: 'Red Light Therapy: Science Behind the Glow',
    titleFr: "Luminothérapie rouge : la science derrière l'éclat",
    bodyEn: 'Red light (630–700nm) penetrates deep into skin tissue, energizing cells to produce more collagen and elastin. Visible results in 8–12 weeks of consistent use.',
    bodyFr: "La lumière rouge (630–700nm) pénètre profondément dans les tissus cutanés, stimulant les cellules à produire plus de collagène et d'élastine. Résultats visibles en 8–12 semaines.",
    stepsEn: [
      'Cleanse face thoroughly — remove all makeup and SPF before treatment',
      'Set device to red light mode (630–700nm wavelength)',
      'Hold device 1–2cm from skin and move slowly across each zone',
      'Spend 1–2 minutes per zone: forehead, cheeks, jaw, neck',
      'Total session: 10–15 minutes, 3–5× per week',
      'Apply serum immediately after — skin absorption is enhanced post-treatment',
    ],
    stepsFr: [
      "Nettoyez soigneusement le visage — retirez tout maquillage et SPF avant le traitement",
      "Réglez l'appareil en mode lumière rouge (longueur d'onde 630–700nm)",
      "Tenez l'appareil à 1–2cm de la peau et déplacez-le lentement sur chaque zone",
      "Consacrez 1–2 minutes par zone : front, joues, mâchoire, cou",
      "Durée totale de séance : 10–15 minutes, 3–5× par semaine",
      "Appliquez un sérum immédiatement après — l'absorption est améliorée après le traitement",
    ],
    category: 'Technology',
    readMinutes: 3,
    points: 10,
  },
  {
    id: '8',
    titleEn: 'Vitamin B3 & B5: The Skin-Strengthening Duo',
    titleFr: 'Vitamines B3 & B5 : le duo renforçant',
    bodyEn: 'Niacinamide (B3) reduces pores and controls sebum. Panthenol (B5) deeply hydrates and accelerates healing. Together they build a resilient skin barrier.',
    bodyFr: "La niacinamide (B3) réduit les pores et contrôle le sébum. Le panthénol (B5) hydrate en profondeur. Ensemble ils renforcent la barrière cutanée.",
    stepsEn: [
      'After cleansing, apply niacinamide (B3) serum to face and neck',
      'Wait 2–3 minutes for it to absorb before layering the next product',
      'Apply panthenol (B5) moisturizer on top to seal in hydration',
      'Use AM and PM — both are safe and gentle for daily use',
      'If combining with Vitamin C: apply Vitamin C first, wait 15 min, then B3',
      'Consistent use for 4+ weeks shows visible pore reduction and smoother texture',
    ],
    stepsFr: [
      "Après le nettoyage, appliquez un sérum niacinamide (B3) sur le visage et le cou",
      "Attendez 2–3 minutes pour l'absorption avant d'appliquer le produit suivant",
      "Appliquez une crème panthénol (B5) par-dessus pour sceller l'hydratation",
      "Utilisez matin et soir — les deux sont doux et sûrs pour un usage quotidien",
      "Si vous combinez avec la vitamine C : appliquez-la en premier, attendez 15 min, puis B3",
      "Une utilisation régulière pendant 4+ semaines montre une réduction visible des pores",
    ],
    category: 'Ingredients',
    readMinutes: 3,
    points: 10,
  },
  {
    id: '9',
    titleEn: 'Jaw & Neck: The Forgotten Zones',
    titleFr: "Mâchoire & cou : les zones oubliées",
    bodyEn: 'The jawline and neck show signs of aging first, yet most routines stop at the chin. Add 2 minutes of drainage massage to define contour and reduce tension.',
    bodyFr: "La mâchoire et le cou montrent les premiers signes de vieillissement, pourtant la plupart des routines s'arrêtent au menton. Ajoutez 2 minutes de massage de drainage.",
    stepsEn: [
      'Apply facial oil or serum to neck and jawline as a base',
      'Lymphatic drainage: stroke downward from ear to collarbone, 5× each side',
      'Jawline contouring: pinch firmly along the bone from chin to ear, 10 reps',
      'Neck stretch: tilt head back gently, apply moisturizer in upward strokes',
      'Extend all skincare products down to your décolleté — never stop at the chin',
      'Repeat daily for 2 minutes — results are visible within 2 weeks',
    ],
    stepsFr: [
      "Appliquez de l'huile ou du sérum sur le cou et la mâchoire comme base",
      "Drainage lymphatique : remontez de l'oreille vers la clavicule, 5× de chaque côté",
      "Contour de la mâchoire : pincez fermement le long de l'os du menton à l'oreille, 10 fois",
      "Étirement du cou : inclinez légèrement la tête en arrière, appliquez la crème vers le haut",
      "Étendez tous vos soins jusqu'au décolleté — ne vous arrêtez jamais au menton",
      "Répétez quotidiennement pendant 2 minutes — les résultats sont visibles en 2 semaines",
    ],
    category: 'Technique',
    readMinutes: 2,
    points: 10,
  },
  {
    id: '10',
    titleEn: 'SPF Every Day: Non-Negotiable',
    titleFr: 'SPF chaque jour : non-négociable',
    bodyEn: 'Up to 80% of visible skin aging is caused by UV exposure — including on cloudy days and indoors. SPF is the single most effective anti-aging product you can use.',
    bodyFr: "Jusqu'à 80% du vieillissement cutané visible est causé par l'exposition aux UV — même par temps nuageux ou à l'intérieur. Le SPF est le produit anti-âge le plus efficace.",
    stepsEn: [
      'Apply SPF as the absolute last step of your morning skincare routine',
      'Use SPF 30 minimum — SPF 50 recommended for daily use',
      'Apply generously: use 1/4 teaspoon for face and neck combined',
      "Don't forget: ears, hairline, back of hands, and décolleté",
      'Reapply every 2 hours if spending time outdoors or sweating',
      'Yes — even on cloudy days, even indoors near windows, every single day',
    ],
    stepsFr: [
      "Appliquez le SPF en toute dernière étape de votre routine matinale",
      "Utilisez au minimum SPF 30 — SPF 50 recommandé pour un usage quotidien",
      "Appliquez généreusement : 1/4 de cuillère à café pour le visage et le cou",
      "N'oubliez pas : oreilles, ligne de cheveux, dos des mains et décolleté",
      "Réappliquez toutes les 2 heures si vous passez du temps dehors ou transpirez",
      "Oui — même par temps nuageux, même en intérieur près des fenêtres, chaque jour",
    ],
    category: 'Protection',
    readMinutes: 2,
    points: 10,
  },
];
